import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import Movies from "../components/Movies";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h2 className={styles.pageTitle}> Movies</h2>
        <Movies />
      </Layout>
    </div>
  );
};

export default Home;
