import type { NextPage } from "next";
import Head from "next/head";
import HomepageItem from "../components/HomepageItem";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.scss";

const Home: NextPage = ({ movies }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>OpenTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h2 className={styles.pageTitle}> Movies</h2>
        <div className={styles.moviesGrid}>
          {movies &&
            movies.data.movies.map((movie: any) => {
              return (
                <HomepageItem
                  key={movie.id}
                  backgroundImage={movie.medium_cover_image}
                  title={movie.title}
                  year={movie.year}
                  genres={movie.genres}
                  movieId={movie.id}
                />
              );
            })}
        </div>
      </Layout>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  const res = await fetch("https://yts.mx/api/v2/list_movies.json");

  const movies = await res.json();

  return {
    props: {
      movies,
    },
  };
}
